# credit: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
name: MTG Art Downloader
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            TARGET: macos
          - os: windows-latest
            TARGET: windows
          - os: ubuntu-latest
            TARGET: linux
    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: |
        poetry install
    - name: Build with PyInstaller
      run: |
        poetry run python build.py ${{ github.ref_name }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./dist/mtg-art-downloader.${{ github.ref_name }}.zip
        name: MTG Art Downloader (${{ matrix.TARGET }})
