# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Test on Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    #----------------------------------------------
    #  -----  install Poetry and Dependencies  ----
    #----------------------------------------------
    - name: Install Poetry & Deps
      run: |
        python -m pip install -U pip poetry
        poetry install
        poetry add types-requests
    #----------------------------------------------
    # Run our Tests w/ Pytest, Type check with mypy
    #----------------------------------------------
    - name: Pytest and Mypy
      run: |
        poetry run pytest lib/tests.py
        poetry run mypy main.py --ignore-missing-imports --exclude requests
        poetry run mypy lib --ignore-missing-imports --exclude requests

  pre-commit:
    #----------------------------------------------
    # Pre-commit hooks check
    #----------------------------------------------
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files
